name: or-demo

on:
  push:
    branches:
      - main
      - dev

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: run for satya or pooja
        if: ${{ github.actor == 'satya' || github.actor == 'pooja' }}
        run: echo "this is ok"
